### ISSUE TITLE
This code is closed for no reason

### ISSUE THREAD

**Issue by danse** [eHealthAfrica/angular-eha.focus-on-invalid#1]
I need approval from two other devs in order to open source this. Please confirm that there is no sensitive information here

**Comment by febeling** [comment]
Looks safe to release for me. :ship:

**Comment by rmehner** [comment]
:+1: (Travis badge in README doesn't work, but that's not sensitive ;))

**Comment by febeling** [comment]
@rmehner true, I looked exclusively for sensitive info.

**Comment by danse** [comment]
yep i am going to set up Travis after opening, because i am too lazy to migrate it. Open Travis is going to be different from closed Travis

**Comment by danse** [comment]
:unlock:

**Comment by febeling** [comment]
:clap: :tada:
